export interface CuratedFilm {
  id: string;
  tmdbId: number;
  title: string;
  year: number;
  director: string;
  posterPath: string;
  overview: string;
  themes: string[];
  letterboxdSlug: string;
}

export const filmThemes = [
  {
    id: "lack-of-purpose",
    name: "Lack of Purpose",
    description: "Feeling directionless, questioning meaning of life",
    keywords: ["purpose", "meaning", "directionless", "lost", "stuck", "aimless", "what should i do", "no goal"],
  },
  {
    id: "grief-loss",
    name: "Grief & Loss",
    description: "Dealing with death of a loved one or significant loss",
    keywords: ["grief", "loss", "death", "died", "passed away", "mourning", "bereavement", "lost someone"],
  },
  {
    id: "burnout",
    name: "Burnout & Exhaustion",
    description: "Overworked, tired, disillusioned with career",
    keywords: ["burnout", "tired", "exhausted", "overwork", "career", "job", "work", "stress", "corporate"],
  },
  {
    id: "heartbreak",
    name: "Heartbreak & Love",
    description: "Relationship ended, unrequited love, trust issues",
    keywords: ["heartbreak", "breakup", "love", "relationship", "divorce", "ex", "alone", "betrayal"],
  },
  {
    id: "anxiety-fear",
    name: "Anxiety & Fear",
    description: "Overwhelmed by fear, unable to take risks",
    keywords: ["anxiety", "fear", "scared", "panic", "worry", "nervous", "afraid", "overthink"],
  },
  {
    id: "identity",
    name: "Identity Crisis",
    description: "Who am I? Questioning self, values, beliefs",
    keywords: ["identity", "who am i", "self", "identity crisis", "change", "transformation", "growing up"],
  },
  {
    id: "anger",
    name: "Anger & Resentment",
    description: "Unable to forgive, holding grudges, rage",
    keywords: ["anger", "resentment", "rage", "bitter", "frustrated", "irritated", "forgive", "grudge"],
  },
  {
    id: "loneliness",
    name: "Loneliness & Connection",
    description: "Feeling isolated, unable to connect with others",
    keywords: ["lonely", "alone", "isolated", "connection", "friend", "social", "alienation", "solitude"],
  },
  {
    id: "guilt-regret",
    name: "Guilt & Regret",
    description: "Haunted by past mistakes, unable to move on",
    keywords: ["guilt", "regret", "mistake", "sorry", "past", "haunted", "forgive myself", "shame"],
  },
  {
    id: "existential",
    name: "Existential Dread",
    description: "Confronting mortality, meaninglessness of existence",
    keywords: ["existential", "death", "mortality", "meaningless", "void", "universe", "why exist"],
  },
  {
    id: "creative-block",
    name: "Creative Block",
    description: "Unable to create, writer's block, imposter syndrome",
    keywords: ["creative", "block", "writer", "artist", "imposter", "inspiration", "create", "stuck"],
  },
  {
    id: "family-conflict",
    name: "Family & Obligation",
    description: "Struggles with family expectations, duty vs desire",
    keywords: ["family", "parent", "mother", "father", "obligation", "duty", "expectation", "home"],
  },
];

export const curatedFilms: CuratedFilm[] = [
  {
    id: "walter-mitty",
    tmdbId: 116745,
    title: "The Secret Life of Walter Mitty",
    year: 2013,
    director: "Ben Stiller",
    posterPath: "",
    overview: "A daydreamer escapes his ordinary life on a global adventure.",
    themes: ["lack-of-purpose"],
    letterboxdSlug: "the-secret-life-of-walter-mitty",
  },
  {
    id: "into-the-wild",
    tmdbId: 591,
    title: "Into the Wild",
    year: 2007,
    director: "Sean Penn",
    posterPath: "",
    overview: "A young man abandons his possessions to journey into the Alaskan wilderness.",
    themes: ["lack-of-purpose", "identity"],
    letterboxdSlug: "into-the-wild",
  },
  {
    id: "ghost-story",
    tmdbId: 414906,
    title: "A Ghost Story",
    year: 2017,
    director: "David Lowery",
    posterPath: "",
    overview: "A ghost returns to his suburban home to watch his grieving wife.",
    themes: ["grief-loss"],
    letterboxdSlug: "a-ghost-story",
  },
  {
    id: "coco",
    tmdbId: 354912,
    title: "Coco",
    year: 2017,
    director: "Lee Unkrich",
    posterPath: "",
    overview: "A boy journeys to the Land of the Dead to discover his family history.",
    themes: ["grief-loss", "family-conflict"],
    letterboxdSlug: "coco-2017",
  },
  {
    id: "the-farewell",
    tmdbId: 565028,
    title: "The Farewell",
    year: 2019,
    director: "Lulu Wang",
    posterPath: "",
    overview: "A family gathers when their matriarch is diagnosed with terminal cancer.",
    themes: ["grief-loss", "family-conflict"],
    letterboxdSlug: "the-farewell",
  },
  {
    id: "office-space",
    tmdbId: 8012,
    title: "Office Space",
    year: 1999,
    director: "Mike Judge",
    posterPath: "",
    overview: "A programmer hates his job and starts a scheme to embezzle money.",
    themes: ["burnout"],
    letterboxdSlug: "office-space",
  },
  {
    id: "sorry-to-bother",
    tmdbId: 488448,
    title: "Sorry to Bother You",
    year: 2018,
    director: "Boots Riley",
    posterPath: "",
    overview: "A telemarketer discovers a magical key to success.",
    themes: ["burnout", "identity"],
    letterboxdSlug: "sorry-to-bother-you",
  },
  {
    id: "eternal-sunshine",
    tmdbId: 38,
    title: "Eternal Sunshine of the Spotless Mind",
    year: 2004,
    director: "Michel Gondry",
    posterPath: "",
    overview: "A couple undergoes a procedure to erase each other from their memories.",
    themes: ["heartbreak"],
    letterboxdSlug: "eternal-sunshine-of-the-spotless-mind",
  },
  {
    id: "500-days",
    tmdbId: 19908,
    title: "500 Days of Summer",
    year: 2009,
    director: "Marc Webb",
    posterPath: "",
    overview: "A man reflects on his relationship with a woman who didn't believe in love.",
    themes: ["heartbreak"],
    letterboxdSlug: "500-days-of-summer",
  },
  {
    id: "the-whale",
    tmdbId: 785084,
    title: "The Whale",
    year: 2022,
    director: "Darren Aronofsky",
    posterPath: "",
    overview: "A reclusive English teacher tries to reconnect with his daughter.",
    themes: ["anxiety-fear", "guilt-regret"],
    letterboxdSlug: "the-whale-2022",
  },
  {
    id: "perfect-days",
    tmdbId: 1022789,
    title: "Perfect Days",
    year: 2023,
    director: "Wim Wenders",
    posterPath: "",
    overview: "A Tokyo toilet cleaner finds contentment in his simple routine.",
    themes: ["lack-of-purpose", "existential"],
    letterboxdSlug: "perfect-days-2023",
  },
  {
    id: "everything-everywhere",
    tmdbId: 545611,
    title: "Everything Everywhere All At Once",
    year: 2022,
    director: "Daniel Kwan & Daniel Scheinert",
    posterPath: "",
    overview: "A woman connects with parallel universe versions of herself.",
    themes: ["identity", "existential", "family-conflict"],
    letterboxdSlug: "everything-everywhere-all-at-once",
  },
  {
    id: "lost-in-translation",
    tmdbId: 153,
    title: "Lost in Translation",
    year: 2003,
    director: "Sofia Coppola",
    posterPath: "",
    overview: "Two Americans form a bond in Tokyo.",
    themes: ["loneliness", "lack-of-purpose"],
    letterboxdSlug: "lost-in-translation",
  },
  {
    id: "her",
    tmdbId: 152601,
    title: "Her",
    year: 2013,
    director: "Spike Jonze",
    posterPath: "",
    overview: "A man develops a relationship with an AI operating system.",
    themes: ["loneliness", "heartbreak"],
    letterboxdSlug: "her",
  },
  {
    id: "drive-my-car",
    tmdbId: 775996,
    title: "Drive My Car",
    year: 2021,
    director: "Ryusuke Hamaguchi",
    posterPath: "",
    overview: "A stage actor deals with grief while directing a play.",
    themes: ["grief-loss", "loneliness"],
    letterboxdSlug: "drive-my-car",
  },
  {
    id: "tree-of-life",
    tmdbId: 8967,
    title: "The Tree of Life",
    year: 2011,
    director: "Terrence Malick",
    posterPath: "",
    overview: "A man reflects on his childhood and the cosmos.",
    themes: ["existential", "guilt-regret", "grief-loss"],
    letterboxdSlug: "the-tree-of-life",
  },
  {
    id: "ikiru",
    tmdbId: 24138,
    title: "Ikiru",
    year: 1952,
    director: "Akira Kurosawa",
    posterPath: "",
    overview: "A bureaucrat finds meaning in life after a terminal diagnosis.",
    themes: ["existential", "lack-of-purpose"],
    letterboxdSlug: "ikiru",
  },
  {
    id: "waking-life",
    tmdbId: 8817,
    title: "Waking Life",
    year: 2001,
    director: "Richard Linklater",
    posterPath: "",
    overview: "A man floats through a dreamworld of philosophical discussions.",
    themes: ["existential", "identity"],
    letterboxdSlug: "waking-life",
  },
  {
    id: "synecdoche-new-york",
    tmdbId: 8289,
    title: "Synecdoche, New York",
    year: 2008,
    director: "Charlie Kaufman",
    posterPath: "",
    overview: "A theater director builds a replica of New York inside a warehouse.",
    themes: ["existential", "creative-block", "identity"],
    letterboxdSlug: "synecdoche-new-york",
  },
  {
    id: "atonement",
    tmdbId: 4347,
    title: "Atonement",
    year: 2007,
    director: "Joe Wright",
    posterPath: "",
    overview: "A young girl's false accusation changes lives forever.",
    themes: ["guilt-regret"],
    letterboxdSlug: "atonement",
  },
  {
    id: "hidden-fortress",
    tmdbId: 11649,
    title: "The Hidden Fortress",
    year: 1958,
    director: "Akira Kurosawa",
    posterPath: "",
    overview: "Two peasants help a general escort a princess across enemy lines.",
    themes: ["anger"],
    letterboxdSlug: "the-hidden-fortress",
  },
  {
    id: "tokyo-story",
    tmdbId: 2657,
    title: "Tokyo Story",
    year: 1953,
    director: "Yasujiro Ozu",
    posterPath: "",
    overview: "Elderly parents visit their adult children in postwar Tokyo.",
    themes: ["family-conflict", "loneliness"],
    letterboxdSlug: "tokyo-story",
  },
  {
    id: "paterson",
    tmdbId: 389549,
    title: "Paterson",
    year: 2016,
    director: "Jim Jarmusch",
    posterPath: "",
    overview: "A bus driver and poet finds beauty in everyday life.",
    themes: ["creative-block", "lack-of-purpose"],
    letterboxdSlug: "paterson",
  },
  {
    id: "after-life",
    tmdbId: 12476,
    title: "After Life",
    year: 1998,
    director: "Hirokazu Kore-eda",
    posterPath: "",
    overview: "The recently dead must choose a single memory to keep for eternity.",
    themes: ["existential", "grief-loss", "guilt-regret"],
    letterboxdSlug: "after-life",
  },
  {
    id: "before-sunrise",
    tmdbId: 76,
    title: "Before Sunrise",
    year: 1995,
    director: "Richard Linklater",
    posterPath: "",
    overview: "A young man and woman meet on a train and spend a night in Vienna.",
    themes: ["heartbreak", "loneliness"],
    letterboxdSlug: "before-sunrise",
  },
  {
    id: "the-graduate",
    tmdbId: 859,
    title: "The Graduate",
    year: 1967,
    director: "Mike Nichols",
    posterPath: "",
    overview: "A young man returns home and is seduced by an older woman.",
    themes: ["lack-of-purpose", "identity"],
    letterboxdSlug: "the-graduate",
  },
  {
    id: "three-colors-blue",
    tmdbId: 109,
    title: "Three Colors: Blue",
    year: 1993,
    director: "Krzysztof Kieślowski",
    posterPath: "",
    overview: "A woman tries to liberate herself from grief after losing her family.",
    themes: ["grief-loss", "identity"],
    letterboxdSlug: "three-colors-blue",
  },
  {
    id: "the-end-of-evangelion",
    tmdbId: 18419,
    title: "The End of Evangelion",
    year: 1997,
    director: "Hideaki Anno",
    posterPath: "",
    overview: "The fate of humanity hangs in the balance as Shinji must make a final choice.",
    themes: ["anxiety-fear", "existential", "loneliness"],
    letterboxdSlug: "the-end-of-evangelion",
  },
  {
    id: "good-will-hunting",
    tmdbId: 211,
    title: "Good Will Hunting",
    year: 1997,
    director: "Gus Van Sant",
    posterPath: "",
    overview: "A janitor at MIT has a gift for mathematics, but struggles with his past.",
    themes: ["identity", "guilt-regret", "lack-of-purpose"],
    letterboxdSlug: "good-will-hunting",
  },
  {
    id: "the-truman-show",
    tmdbId: 957,
    title: "The Truman Show",
    year: 1998,
    director: "Peter Weir",
    posterPath: "",
    overview: "A man discovers his entire life is a television show.",
    themes: ["identity", "anxiety-fear"],
    letterboxdSlug: "the-truman-show",
  },
  {
    id: "falcon-lake",
    tmdbId: 1126323,
    title: "Falcon Lake",
    year: 2022,
    director: "Charlotte Le Bon",
    posterPath: "",
    overview: "A teenage boy's family vacation turns into a haunting summer romance.",
    themes: ["heartbreak", "grief-loss"],
    letterboxdSlug: "falcon-lake",
  },
  {
    id: "aftersun",
    tmdbId: 949092,
    title: "Aftersun",
    year: 2022,
    director: "Charlotte Wells",
    posterPath: "",
    overview: "A woman reflects on a holiday she took with her father years ago.",
    themes: ["grief-loss", "family-conflict", "guilt-regret"],
    letterboxdSlug: "aftersun",
  },
  {
    id: "past-lives",
    tmdbId: 1058694,
    title: "Past Lives",
    year: 2023,
    director: "Celine Song",
    posterPath: "",
    overview: "Two childhood friends reconnect after decades apart.",
    themes: ["heartbreak", "identity", "guilt-regret"],
    letterboxdSlug: "past-lives",
  },
  {
    id: "naked",
    tmdbId: 836,
    title: "Naked",
    year: 1993,
    director: "Mike Leigh",
    posterPath: "",
    overview: "An intellectual drifter wanders London having intense conversations.",
    themes: ["existential", "anger", "loneliness"],
    letterboxdSlug: "naked-1993",
  },
  {
    id: "spring-summer",
    tmdbId: 113,
    title: "Spring, Summer, Fall, Winter... and Spring",
    year: 2003,
    director: "Kim Ki-duk",
    posterPath: "",
    overview: "The cycle of life as seen through seasons at a floating monastery.",
    themes: ["existential", "guilt-regret", "anger"],
    letterboxdSlug: "spring-summer-fall-winter-and-spring",
  },
  {
    id: "asako",
    tmdbId: 490132,
    title: "Asako I & II",
    year: 2018,
    director: "Ryusuke Hamaguchi",
    posterPath: "",
    overview: "A woman falls for a man who resembles her lost love.",
    themes: ["heartbreak", "identity"],
    letterboxdSlug: "asako-i-and-ii",
  },
  {
    id: "the-souvenir",
    tmdbId: 515554,
    title: "The Souvenir",
    year: 2019,
    director: "Joanna Hogg",
    posterPath: "",
    overview: "A film student's relationship with a mysterious man shapes her art.",
    themes: ["creative-block", "heartbreak", "identity"],
    letterboxdSlug: "the-souvenir",
  },
  {
    id: "climax",
    tmdbId: 440472,
    title: "Climax",
    year: 2018,
    director: "Gaspar Noé",
    posterPath: "",
    overview: "A dance troupe's celebration descends into chaos when LSD is spiked.",
    themes: ["anxiety-fear", "identity"],
    letterboxdSlug: "climax-2018",
  },
  {
    id: "the-seventh-seal",
    tmdbId: 490,
    title: "The Seventh Seal",
    year: 1957,
    director: "Ingmar Bergman",
    posterPath: "",
    overview: "A knight plays chess with Death during the plague.",
    themes: ["existential", "anxiety-fear"],
    letterboxdSlug: "the-seventh-seal",
  },
  {
    id: "the-fire-within",
    tmdbId: 625,
    title: "The Fire Within",
    year: 1963,
    director: "Louis Malle",
    posterPath: "",
    overview: "A man leaving rehab visits old friends before making a fateful decision.",
    themes: ["loneliness", "existential", "lack-of-purpose"],
    letterboxdSlug: "the-fire-within",
  },
  {
    id: "safe",
    tmdbId: 11394,
    title: "Safe",
    year: 1995,
    director: "Todd Haynes",
    posterPath: "",
    overview: "A housewife develops a mysterious environmental illness.",
    themes: ["anxiety-fear", "identity"],
    letterboxdSlug: "safe-1995",
  },
  {
    id: "maborosi",
    tmdbId: 33999,
    title: "Maborosi",
    year: 1995,
    director: "Hirokazu Kore-eda",
    posterPath: "",
    overview: "A young widow remarries and moves to a coastal town, haunted by her past.",
    themes: ["grief-loss", "guilt-regret"],
    letterboxdSlug: "maborosi",
  },
  {
    id: "still-walking",
    tmdbId: 33998,
    title: "Still Walking",
    year: 2008,
    director: "Hirokazu Kore-eda",
    posterPath: "",
    overview: "A family gathers to commemorate the death of the eldest son.",
    themes: ["grief-loss", "family-conflict", "guilt-regret"],
    letterboxdSlug: "still-walking",
  },
  {
    id: "the-400-blows",
    tmdbId: 148,
    title: "The 400 Blows",
    year: 1959,
    director: "François Truffaut",
    posterPath: "",
    overview: "A misunderstood boy runs away from his troubled home.",
    themes: ["family-conflict", "identity", "loneliness"],
    letterboxdSlug: "the-400-blows",
  },
  {
    id: "manchester-by-the-sea",
    tmdbId: 389569,
    title: "Manchester by the Sea",
    year: 2016,
    director: "Kenneth Lonergan",
    posterPath: "",
    overview: "A man returns to his hometown to care for his nephew after his brother's death.",
    themes: ["grief-loss", "guilt-regret"],
    letterboxdSlug: "manchester-by-the-sea",
  },
  {
    id: "fallen-angels",
    tmdbId: 111,
    title: "Fallen Angels",
    year: 1995,
    director: "Wong Kar-wai",
    posterPath: "",
    overview: "A hitman, his agent, and a mute ex-con's lives intertwine in Hong Kong.",
    themes: ["loneliness", "heartbreak"],
    letterboxdSlug: "fallen-angels",
  },
  {
    id: "in-the-mood-for-love",
    tmdbId: 843,
    title: "In the Mood for Love",
    year: 2000,
    director: "Wong Kar-wai",
    posterPath: "",
    overview: "Two neighbors in 1960s Hong Kong form a bond over their spouses' infidelities.",
    themes: ["heartbreak", "loneliness", "guilt-regret"],
    letterboxdSlug: "in-the-mood-for-love",
  },
  {
    id: "taste-of-cherry",
    tmdbId: 11267,
    title: "Taste of Cherry",
    year: 1997,
    director: "Abbas Kiarostami",
    posterPath: "",
    overview: "A man drives around Tehran looking for someone to bury him after suicide.",
    themes: ["existential", "loneliness", "lack-of-purpose"],
    letterboxdSlug: "taste-of-cherry",
  },
  {
    id: "wild-strawberries",
    tmdbId: 792,
    title: "Wild Strawberries",
    year: 1957,
    director: "Ingmar Bergman",
    posterPath: "",
    overview: "An old professor revisits his past while traveling to receive an honor.",
    themes: ["existential", "guilt-regret", "family-conflict"],
    letterboxdSlug: "wild-strawberries",
  },
  {
    id: "the-apartment",
    tmdbId: 284,
    title: "The Apartment",
    year: 1960,
    director: "Billy Wilder",
    posterPath: "",
    overview: "A man lets his apartment be used for his boss's extramarital affairs.",
    themes: ["heartbreak", "burnout"],
    letterboxdSlug: "the-apartment",
  },
  {
    id: "whiplash",
    tmdbId: 244786,
    title: "Whiplash",
    year: 2014,
    director: "Damien Chazelle",
    posterPath: "",
    overview: "A jazz drummer pushes himself to the brink under a demanding teacher.",
    themes: ["burnout", "creative-block", "anger"],
    letterboxdSlug: "whiplash",
  },
];

export function getFilmByTheme(themeId: string): CuratedFilm[] {
  return curatedFilms.filter((f) => f.themes.includes(themeId));
}

export function getRandomFilmByTheme(themeId: string): CuratedFilm | null {
  const films = getFilmByTheme(themeId);
  if (films.length === 0) return null;
  return films[Math.floor(Math.random() * films.length)];
}

export function findThemesInText(text: string): string[] {
  const lower = text.toLowerCase();
  const matched: string[] = [];
  for (const theme of filmThemes) {
    const matchCount = theme.keywords.filter((k) => lower.includes(k)).length;
    if (matchCount > 0) {
      matched.push(theme.id);
    }
  }
  return matched;
}

export function getThemeById(id: string) {
  return filmThemes.find((t) => t.id === id);
}
